### ISSUE TITLE
Add us to http://www.sonarqube.org/

### ISSUE THREAD

**Issue by yossigil** [SpartanRefactoring/Spartanizer#124]
Here is the link: http://www.sonarqube.org/

**Comment by yossigil** [comment]
News?

**Comment by M4tt30rru** [comment]
Working on it. I supposed that for today the priority was the other topic since we had a meeting in the afternoon, so I focused more on that for today.

**Comment by M4tt30rru** [comment]
I managed to add a repository on sonarqube. However, all the procedure must be performed using the owner account. I created a fork of Spartanizer on a different GitHub account and I was able to add the plugin on sonarqube. 

Here is the link:

[https://sonarqube.com/overview?id=il.org.spartan%3Ail.org.spartan.refactoring](https://sonarqube.com/overview?id=il.org.spartan%3Ail.org.spartan.refactoring)

However, from the present account I can't do the same, because I am only a contributor.
@yossigil I was looking for the opportunity to add multiple owner to a project (maybe using the organization property?).

Here are the instructions to do it from the owner account.

1) Log in in Sonarqube.org using your GitHub account (it **must** be the same you used to create the repository). In the menu Profile -> Security you have to create a key (later on: secretvalue). 

2) Encrypt the key using the following command.

`travis encrypt SONAR_TOKEN=secretvalue`

_secretvalue_ is the one taken in (1).
It is better to be in the repository folder. 
Otherwise, add -r owner/repository to the reported instruction.

In case you do not already installed it, you need to install _travis_.

`gem install travis`

and in case it does not work it may be the case to install ruby-dev.

Source: [https://docs.travis-ci.com/user/encryption-keys/#Usage](https://docs.travis-ci.com/user/encryption-keys/#Usage)

3) Add the following instruction to the .travis.yml file

```
addons:
  sonarqube: true
env:
  global:
    - secure: ********* # defines SONAR_TOKEN=abcdef0123456789
script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarQube analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.login=$SONAR_TOKEN

```
where ************ is the place of the encrypted token obtained in (2).

Source: [https://docs.travis-ci.com/user/sonarqube/](https://docs.travis-ci.com/user/sonarqube/)

4) Create a sonar-project.properties file with the following content (the basic one).

```
# must be unique in a given SonarQube instance
sonar.projectKey=sonar:spartanizer
# this is the name displayed in the SonarQube UI
sonar.projectName=Spartanizer
sonar.projectVersion=2.5
 
# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# Since SonarQube 4.2, this property is optional if sonar.modules is set. 
# If not set, SonarQube starts looking for source code from the directory containing 
# the sonar-project.properties file.
sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
```

and place it on the root folder of the project.

Source: [http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner](http://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner)

It should compile in about 13 minutes.
